#ifndef COMMONDEFINES_HPP
#define COMMONDEFINES_HPP

const int ROAD_WIDTH = 40;
const int ROAD_LENGHT = 20;
const int DISTANCE = 400;

const enum Lane {
	LANE_FIRST = 0,
	LANE_SECOND,
	LANE_THIRD,
	LANE_FOURTH,
	LANE_OBSTACLE
};

#endif COMMONDEFINES_HPP